# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Phoenix CI (Test + Release)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        ports: ['5432:5432']
        env:
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}

        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MIX_ENV: test
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Elixir & Erlang
      uses: erlef/setup-beam@v1.18.2 # v1.16.0
      with:
        elixir-version: '1.15.2' # [Required] Define the Elixir version
        otp-version: '26.0'      # [Required] Define the Erlang/OTP version

    - name: Install Hex & Rebar
      run: |
        mix local.hex --force
        mix local.rebar --force
        
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
        
    - name: Output Elixir version
      run: elixir --version
      
    - name: Output PostgreSQL version
      run: psql --version
      
    - name: Install dependencies
      run: mix deps.get

    - name: Create & migrate database
      run: |
        mix ecto.create
        mix ecto.migrate
      
    - name: Run tests
      run: mix test

    - name: Build production release
      env:
        MIX_ENV: prod
        SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}
        DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
      run: |
        # Install only production deps
        mix deps.get --only prod
        mix compile

        # Generate release artifact
        mix phx.gen.release

    - name: Upload phoenix release
      uses: actions/upload-artifact@v4
      with:
        name: phoenix-release
        path: _build/prod/rel
